### ISSUE TITLE
Does not work on MacOS

### ISSUE THREAD

**Issue by Dreamkeeper66666** [yenw/LeelaZero_PhoenixGo#10]
I just compiled the source code of leelazero-0.15 and it worked when I opened through command line. But it seems that it doesn't work with lizzie v0.5. I am compiling using the cpu-only version. So I just commented #define USE_OPENCL out while compiling. Could you give me some idea about what's probably gone wrong?  Does it have something to do with the branch since lizzie should work with leelaz which is compiled from "next" branch. Thanks!

**Comment by yenw** [comment]
I release the leelazero-phoenix-go v0.16. And it should be work with lizzie v0.6.

**Comment by Dreamkeeper66666** [comment]
@yenw It works now, thanks. By the way, is there any way to convert the weights into lz format like elf? It would be much more convenient!!

**Comment by yenw** [comment]
The network structure of LZ and ELF are the ResNet(a), but PhoenixGo uses the ResNetV2(b). 
![](https://www.pyimagesearch.com/wp-content/uploads/2017/03/imagenet_resnet_identity.png)
So we can't convert it.

**Comment by l1t1** [comment]
https://blog.csdn.net/lanran2/article/details/80247515

**Comment by Dreamkeeper66666** [comment]
Got it, thanks so much! @yenw @l1t1

**Comment by alreadydone** [comment]
It should be possible to assign to the PhoenixGo network a different version number, so we can support both LZ and PhoenixGo networks in the same binary, like how sai-dev/sai supports both LZ and SAI networks.
