### ISSUE TITLE
could you release the version 0.17 and windows binary

### ISSUE THREAD

**Issue by l1t1** [yenw/LeelaZero_PhoenixGo#12]
if the program could support both lz weight and PhoenixGo weight, it would be better

**Comment by l1t1** [comment]
just like https://github.com/leela-zero/leela-zero/issues/2272

**Comment by yenw** [comment]
I think it would be better to let GCP support the common weight format like TensorFlow/PyTorch/MXNet.

If the program could support all weight, it would be better.

**Comment by yenw** [comment]
By the way, my Windows 7 has only 32 bits G++ and 4G memory. So when the LZ version is greater than 0.15, it is inconvenient to compile. I apologize for this.

**Comment by l1t1** [comment]
thank you
as i know little about cnn programing, could you explain how to  implement the common  interface or create a pr at the repository of leelazero?

**Comment by yenw** [comment]
https://www.tensorflow.org/guide/low_level_intro#graph
http://mxnet.incubator.apache.org/versions/master/tutorials/basic/symbol.html

**Comment by l1t1** [comment]
thank you 
@y-ich said his app does not care  architecture of neural network at https://github.com/new3Rs/a_master_of_go/issues/76#issuecomment-480551317
