### ISSUE TITLE
How to run these weights and engines on Lizzie 0.15 & Sabaki?

### ISSUE THREAD

**Issue by SHKD13** [yenw/LeelaZero_PhoenixGo#13]
Why all the weights and engines from here are not working? Including the ones from here:
https://github.com/leela-zero/leela-zero/issues/1477
Both for GPU and CPU. No combination of them can't work on both of Lizzie and Sabaki (it says "connection failed"), while all others engines & weights of Leela Zero, Leela Master, ELF or MiniGo are working perfect?
Can You please help me how to run LeelaZero_PhoenixGo?

**Comment by yenw** [comment]
* Weights
   * V1: https://github.com/yenw/LeelaZero_PhoenixGo/releases/download/v1/PhoenixGo_v1.txt.gz
* Leela Zero
  * Windows
     * CPU: https://github.com/yenw/LeelaZero_PhoenixGo/releases/download/v2/leelaz_win_x86_cpu.exe.zip
     * GPU: https://github.com/yenw/LeelaZero_PhoenixGo/releases/download/v2/leelaz_win_x86_gpu_opencl.exe.zip

**Comment by SHKD13** [comment]
It's not working at all :( Please, can You tell me what am I doing wrong? 

![Screenshot_3](https://user-images.githubusercontent.com/39368053/56459156-52fcf880-6398-11e9-9be9-f4985a5ad66c.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/39368053/56459161-585a4300-6398-11e9-8008-7602ef6a82a3.jpg)

**Comment by yenw** [comment]
-g -w "E:\Networks\PhoenixGo v1\PhoenixGo_v1.txt" -t4 --noponder time_settings 0 60 1

**Comment by SHKD13** [comment]
@yenw 
Okay, and what arguments should I type in Sabaki GUI to make PhoenixGo engine and its weights file work? 
Sorry for looking like noob, I am not a programmer :)

**Comment by yenw** [comment]
In addition to the weight name and program name, it is the same as you use LZ.
By the way, it's best not to have spaces in the folder name.
