### ISSUE TITLE
Could not load weights by LeelaZero 0.15 x64?

### ISSUE THREAD

**Issue by ivysrono** [yenw/LeelaZero_PhoenixGo#5]
Weights:
https://github.com/yenw/LeelaZero_PhoenixGo/releases/download/v1/PhoenixGo_v1.txt.gz

Error:
![default](https://user-images.githubusercontent.com/2649544/40573601-4fd8d642-60f6-11e8-833e-640931cb45ad.png)
![default](https://user-images.githubusercontent.com/2649544/40574161-577e03a4-6100-11e8-9f7f-95e9823e5cbc.png)

Config:
![default](https://user-images.githubusercontent.com/2649544/40573600-4d596abc-60f6-11e8-8c51-9acad9923e10.png)

OpenGo is working fine.

**Comment by l1t1** [comment]
so @yenw supply a program, not only the weight

see https://github.com/gcp/leela-zero/issues/1477
