### ISSUE TITLE
linux cpu version cannot run

### ISSUE THREAD

**Issue by l1t1** [yenw/LeelaZero_PhoenixGo#6]
./leelaz: error while loading shared libraries: libboost_program_options.so.1.58.0: cannot open shared object file: No such file or directory
uname -a
2.6.32-279.2.1.el6.x86_64 #1 SMP Tue Aug 14 11:42:24 CST 2012 x86_64 x86_64 x86_64 GNU/Linux

**Comment by yenw** [comment]
Sorry for this.
I forget to compiler my boost with static libraries.
You can compiler it yourself or install boost 1.58.

**Comment by l1t1** [comment]
thanks

**Comment by l1t1** [comment]
must boost be installed as source?
can my gcc build boost source?
$ gcc --version
gcc (GCC) 4.4.6 20120305 (Red Hat 4.4.6-4)

**Comment by yenw** [comment]
I'm not familiar with Red Hat. So I don't know how to install boost1.58 with yum.
I think building boost from source with your gcc should be OK.

**Comment by l1t1** [comment]
./bootstrap.sh  --prefix=/home/oracle/boost158
```
Building Boost.Build engine with toolset gcc... tools/build/src/engine/bin.linuxx86_64/b2
Detecting Python version... 2.6
Detecting Python root... /usr
Unicode/ICU support for Boost.Regex?... not found.
Generating Boost.Build configuration in project-config.jam...

Bootstrapping is done. To build, run:

    ./b2
```
./b2 toolset=gcc
```
Performing configuration checks

    - 32-bit                   : no
    - 64-bit                   : yes
    - arm                      : no
    - mips1                    : no
    - power                    : no
    - sparc                    : no
    - x86                      : yes

Building the Boost C++ Libraries.


    - lockfree boost::atomic_flag : yes
    - has_icu builds           : no
warning: Graph library does not contain MPI-based parallel components.
note: to enable them, add "using mpi ;" to your user-config.jam
```
