### ISSUE TITLE
Value of a parameter

### ISSUE THREAD

**Issue by alreadydone** [yenw/LeelaZero_PhoenixGo#9]
https://github.com/alreadydone/lz/commit/74777dcfe879570041328166983c6f716ccddc96#diff-ede74db51bef85d4bbaf2ee65b64a513R97
PhoenixGo uses c_puct = 2.5 but I think they use values in the range [-1,1] while LZ uses values (winrates) in the range [0,1], so in my opinion when you translate that to LZ you should put c_puct = 2.5/2 = 1.25.

**Comment by alreadydone** [comment]
Also I think policy temperature is not enabled:
https://github.com/Tencent/PhoenixGo/blob/4d9c496e05fedba09f3343b27b73e72417d83fd7/etc/mcts_1gpu.conf#L25
https://github.com/Tencent/PhoenixGo/blob/2278ed1e8a3563c8e66d344c93fe75b933e834dc/mcts/mcts_engine.cc#L307
So cfg_softmax_temp should still be 0, not 0.67.

**Comment by yenw** [comment]
Thank you for your correction.
